### PR TITLE
Switch to LTRData.DiscUtils fork

### LINKED ISSUE #59: MultiExtractor DMG parsing
Using discutils.  Followup from microsoft/OSSGadget#61

### LINKED ISSUE #93: GC thread exception when extracting corrupt wim file
Because of a bug in DiscUtils.Wim (see https://github.com/DiscUtils/DiscUtils/pull/263) extracting the attached image will throw an exception on the GC thread and bring the entire application down.

I have low hope in getting that PR merged since the maintainers of DiscUtils seams absent. 
Can you think of any other other workaround?

[TestDataCorruptWim.zip](https://github.com/microsoft/RecursiveExtractor/files/9831905/TestDataCorruptWim.zip)

### LINKED ISSUE #144: Migrate to LTRData/DiscUtils
Per report in #93 LTRData now publishes a nuget of their fork of diskutils (https://www.nuget.org/packages/LTRData.DiscUtils.Core). We should try to migrate to this fork as it is more actively maintained.

### PR DESCRIPTION
**Pull request by Erik-White**
Closes #144, fixes #93, fixes #59

The current fork of DiscUtils is almost abandoned at this point. The LTRData fork is much further ahead and has made some great performance improvements and bug fixes. Moving to the newer fork would help resolve some existing issues, as well as make future fixes much easier to resolve.

- [x] Merge ReadOnlySpan<char>.Split fix to LTRData.Library, see: https://github.com/LTRData/Library/pull/1
- [x] Merge WIM fixes to LTRData.DiskUtils, see: https://github.com/LTRData/DiscUtils/pull/3
- [x] Update to latest LTRData.DiskUtils in RecursiveExtractor
- [x] Add test cases for DMG
- [x] Add test cases for WIM
- [x] Fix any other remaining tests in RecursiveExtractor

### CODE REVIEW

**Comment by Erik-White** [comment]
@microsoft-github-policy-service agree

File: RecursiveExtractor/Extractors/WimExtractor.cs [hunk 1]
```diff
@@ -107,8 +104,12 @@ public IEnumerable<FileEntry> Extract(FileEntry fileEntry, ExtractorOptions opti
             {
                 for (var i = 0; i < baseFile.ImageCount; i++)
                 {
-                    var image = baseFile.GetImage(i);
-                    foreach (var file in image.GetFiles(image.Root.FullName, "*.*", SearchOption.AllDirectories))
+                    if (!TryGetImage(baseFile, i, out var image))
```
Comment (Erik-White) [inline RecursiveExtractor/Extractors/WimExtractor.cs:107]: DiscUtils returns a `WimFile` with `ImageCount` == 1, but there doesn't appear to be any valid `WimFileSystem` that can be retrieved. As far as I can see that's not due to a bug in DiscUtils, it's just doing the best it can with invalid data.

I'm totally sure how you would want to handle an image that can't be retrieved, but this is my proposal.

**Comment by Erik-White** [comment]
@gfs I think this is ready to go now. All the tests are passing, it just needs checking over to see if you think the LTRData fork of DiscUtils is ready for use.

**Comment by gfs** [comment]
@Erik-White awesome. I'm running pipeline tests now and I'll aim to give this a thorough review tomorrow.

File: RecursiveExtractor/Extractors/WimExtractor.cs (hunk 1 above)
Comment (gfs) [reply RecursiveExtractor/Extractors/WimExtractor.cs:107]: I think this should respect the ExtractSelfOnFail argument, see here for an example of a similar handler for zips. https://github.com/microsoft/RecursiveExtractor/blob/ac94200eeb62942213bb9ac0e88624c934e4e496/RecursiveExtractor/Extractors/ZipExtractor.cs#L66

I can add that to the PR.

Comment (gfs) [reply RecursiveExtractor/Extractors/WimExtractor.cs:107]: I think this approach is fine. I have added a debug message for when an image fails to extract. The other approach I can think of is to set failed archive and extract self on fail if all images fail to extract from a WIM but in the cases that a  partial extraction succeeds I think we generally err on the side of best effort extraction of as much as possible.

**Review by gfs — APPROVED** [review]
LGTM. Thanks @Erik-White for the contribution!

**Review by gfs — COMMENTED** [review]
Upon closer inspection it looks like this does not resolve #59. Need to add DMG type detection to MiniMagic and to add a DMG extractor.

**Comment by gfs** [comment]
Implemented DMG extractor and added compatible DMG file.

**Review by gfs — APPROVED** [review]

**Comment by gfs** [comment]
Test failure is related to different invalid path character definitions between net4.8 and net core. See https://github.com/dotnet/runtime/issues/63383.

Will aim to determine which character is the issue and develop a new sample tomorrow.

File: RecursiveExtractor/Extractors/WimExtractor.cs (hunk 1 above)
Comment (Erik-White) [reply RecursiveExtractor/Extractors/WimExtractor.cs:107]: ok sounds good!

File: .github/workflows/publish-code-coverage.yml
Comment (Erik-White) [inline .github/workflows/publish-code-coverage.yml:1]: Just to double check, was it intentional to remove these two workflows?

**Comment by Erik-White** [comment]
The problem with the DMG test is due to a file entry that has an invalid character in the name: `".HFS+ Private Directory Data\r"`
I can't see a difference in the invalid character list for .NET4.8 vs other versions, but there is a difference in the path handling:
https://referencesource.microsoft.com/#mscorlib/system/io/path.cs,1197
vs
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/Path.cs#L685C3-L685C103

We end up calling [Path.Combine from DiscUtils](https://github.com/LTRData/DiscUtils/blob/LTRData.DiscUtils-initial/Library/DiscUtils.Core/Internal/Utilities.cs#L208) and I wonder if that helper method should maybe have a `#if NET481_OR_GREATER` conditional instead of `#if NET461_OR_GREATER`.

The other option is to change the file entry name in the test data, but I'm not sure what's best. Is this a scenario that needs to be tested?

File: .github/workflows/publish-code-coverage.yml
Comment (gfs) [reply .github/workflows/publish-code-coverage.yml:1]: Yes this was intentional. Not directly related to the dependency change, its just some clean up work that needed to be done.

**Comment by gfs** [comment]
> The problem with the DMG test is due to a file entry that has an invalid character in the name: `".HFS+ Private Directory Data\r"` I can't see a difference in the invalid character list for .NET4.8 vs other versions, but there is a difference in the path handling: https://referencesource.microsoft.com/#mscorlib/system/io/path.cs,1197 vs https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/IO/Path.cs#L685C3-L685C103
> 
> We end up calling [Path.Combine from DiscUtils](https://github.com/LTRData/DiscUtils/blob/LTRData.DiscUtils-initial/Library/DiscUtils.Core/Internal/Utilities.cs#L208) and I wonder if that helper method should maybe have a conditional that excludes .NET framework i.e. `#if NETSTANDARD || NETCOREAPP`.
> 
> The other option is to change the file entry name in the test data, but I'm not sure what's best. Is this a scenario that needs to be tested?

This is an issue I've had to resolve at other times in Recursive Extractor in order to be able to use Path.Combine - https://github.com/microsoft/RecursiveExtractor/blob/ac94200eeb62942213bb9ac0e88624c934e4e496/RecursiveExtractor/FileEntry.cs#L191.

I think I see a couple options here:
1. A patch to DiscUtils to sanitize file names for the platform before calling Path.Combine
2. Exclude DMG support from Recursive Extractor on netstandard 2.1/net4.8
3. Create a sample file which doesn't contain the `.HFS+ Private Directory Data` (I'm not positive this is possible - or desirable - I created this sample file with pretty standard `hdiutil` arguments on OS X from a folder containing two text files.)

Either way its likely prudent to add some extra exception handling as this exception bubbling up to the user does violate one of the design principles I try to follow for this project - that in general unparseable/malformed archives should not throw exceptions. https://github.com/microsoft/RecursiveExtractor/#exceptions

As for if this case is needed - we need a test case for DMG parsing, but this file in particular is not special. However, this file does represent a relatively naiive DMG that I imagine someone may create, so it would be nice if we could support it, and it would be nice to keep feature parity as much as possible between different runtimes. 

I think the ideal solution is probably option 1, perhaps using a mechanism like the one I linked above in `FileEntry.cs`.

**Comment by gfs** [comment]
@Erik-White, got a chance to look at the discutils code you linked. I think I agree the simplest fix may be to change

```csharp
#if NET461_OR_GREATER || NETSTANDARD || NETCOREAPP
        return Path.Combine(a, b);
#else
```
to
```csharp
#if NETSTANDARD || NETCOREAPP
        return Path.Combine(a, b);
#else
```

**Comment by gfs** [comment]
I found the two locations with the differing lists of invalid path chars.

Net 4.8: https://referencesource.microsoft.com/#mscorlib/system/io/pathinternal.cs,32
NetCore (Windows): https://github.com/dotnet/runtime/blob/82bea3fe096185a337bc7a89e4649421215a10d3/src/libraries/System.Private.CoreLib/src/System/IO/Path.Windows.cs#L24

At a minimum it looks like at least `"`, `>` and `<` were removed between framework and core.

**Comment by Erik-White** [comment]
> At a minimum it looks like at least ", > and < were removed between framework and core.

Sorry, I should have been clearer, I meant characters that affected the failing test 😃 


Changing to `#if NETSTANDARD || NETCOREAPP` would be nice and simple. Just need to check two things I think:

- Does it have any unintended effects elsewhere in DiscUtils (or RecursiveExtractor)?
- What is the implementation for NETSTANDARD? Is it the same as .NET Framework or Core?

**Comment by gfs** [comment]
> > At a minimum it looks like at least ", > and < were removed between framework and core.
> 
> Sorry, I should have been clearer, I meant characters that affected the failing test 😃
> 
> Changing to `#if NETSTANDARD || NETCOREAPP` would be nice and simple. Just need to check two things I think:
> 
>     * Does it have any unintended effects elsewhere in DiscUtils (or RecursiveExtractor)?
> 
>     * What is the implementation for NETSTANDARD? Is it the same as .NET Framework or Core?

Ah okay, yes, sorry missed what you meant. It also doesn't appear to me either that we have any of those characters here (perhaps the \r at the end of what you clipped above?).

I opened a PR with the change here, and validated locally by referencing the net code from recursive extractor that it seems to resolve the test issue with net4.8: https://github.com/LTRData/DiscUtils/pull/4 . all the DiscUtils tests still pass without modification - but it would be hard for me to speak if it had some other unintended effect not covered by the tests.

I'm not totally sure on if netstandard should be included in the directive or not, I think there's a reasonable argument to only use Path.Combine on netcoreapp, but I think this is the minimal change which resolves the issue we see here.

**Comment by Erik-White** [comment]
Nice! We just need DiscUtils with the latest fix and then hopefully it's all good to go

**Comment by Erik-White** [comment]
Your fix is now in with the latest DiscUtils and the tests are green! Everything looks good from my side, nice work with the DmgExtractor 🥇

**Comment by gfs** [comment]
Nice. I'll give it one more look over and likely merge today.

**Review by scovetta — APPROVED** [review]

**Comment by gfs** [comment]
Thanks again @Erik-White for your contribution!

**Comment by Erik-White** [comment]
Fantastic, thanks for all your work on this project!
